BASE_URL_INKIDIA_DZ = "https://inkidia.com.dz/"
BASE_URL_MOALIM = "https://www.moalim-dz.net/moalim_v2/login/index.php"
BASE_URL_DELTALOG_DZ ="https://www.deltalog.dz/"
BASE_URL_GLPI = "https://deltalog.dz/support/front/central.php"
BASE_URL_preprod = "http://192.168.20.117:8080/moalim_v2/login/index.php"
